// <auto-generated />
namespace Igra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangetypeofPlayer1andPlayer2inGames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangetypeofPlayer1andPlayer2inGames));
        
        string IMigrationMetadata.Id
        {
            get { return "201807032221270_Change type of Player1 and Player2 in Games"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
